### PR TITLE
April release

### PR DESCRIPTION
**Pull request by codyrobert**
This updates the design for the tour to match the main site.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/151)

 
 
 
 
 
 

Tour Preview: [Dgraph Preview](https://dgraph-tour-4852dd1496-61346.surge.sh)

### CODE REVIEW

**Comment by danielmai** [comment]
@MichelDiz can you review this?

**Review by MichelDiz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/151)* status: 0 of 63 files reviewed, 1 unresolved discussion (waiting on @codyrobert, @danielmai, and @MichaelJCompton)

*[a discussion](https://reviewable.io/reviews/dgraph-io/tutorial/151#-M6aySzQA9y3JDuLfVGl:-M6aySzQA9y3JDuLfVGm:b-ncbhfs) (no related file):*
@codyrobert  the layout looks nice. But I have found some issues.

1 -  Minor - On safari the navbar (page-subnav) has some issues. It is adding spaces bellow.
2 - Can we make the block "lesson__content" wider? something like width: 60%; when not in company of the runnable-pane?
3 -  The box "CHANGE DGRAPH ALPHA URL" has issues in the input position. Strangely if we remove padding: 26px 12px 6px 12px; works nicely.
4 - The runnable-pane ENDPOINT: /MUTATE is kind of messi in Safari, but it is fine in Firefox and Chrome.
5 - Feels like there's nos way to go back to "/" If we click in dgraph's logo it will go to the main site. Not the beginning of the Tour.
6 -  Is possible to bring back the version drop-down? if not so, we can solve this later.
7 - "More resources" icons are missing in local env. Thats okay?

Cheers.

---

**Comment by codyrobert** [comment]
Thanks @MichelDiz. I believe I've fixed everything except number 6 though I'm unsure how to re-trigger the preview build to see these changes. Of note, several of these edits are in the main repo's css file.

For number 5, the intent with tour now existing under the umbrella of the main site, you would navigate back to the home of tour by clicking via 'Learn' > 'Interactive Tour'.

**Review by codyrobert — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/151)* status: 0 of 63 files reviewed, 1 unresolved discussion (waiting on @danielmai, @MichaelJCompton, and @MichelDiz)

*[a discussion](https://reviewable.io/reviews/dgraph-io/tutorial/151#-M6aySzQA9y3JDuLfVGl:-M6exLyCA_YFTeyOEMp_:b-896fix) (no related file):*
<details><summary><i>Previously, MichelDiz (Michel Diz) wrote…</i></summary><blockquote>

@codyrobert  the layout looks nice. But I have found some issues.

1 -  Minor - On safari the navbar (page-subnav) has some issues. It is adding spaces bellow.
2 - Can we make the block "lesson__content" wider? something like width: 60%; when not in company of the runnable-pane?
3 -  The box "CHANGE DGRAPH ALPHA URL" has issues in the input position. Strangely if we remove padding: 26px 12px 6px 12px; works nicely.
4 - The runnable-pane ENDPOINT: /MUTATE is kind of messi in Safari, but it is fine in Firefox and Chrome.
5 - Feels like there's nos way to go back to "/" If we click in dgraph's logo it will go to the main site. Not the beginning of the Tour.
6 -  Is possible to bring back the version drop-down? if not so, we can solve this later.
7 - More resources icons are missing in local env. Thats okay?

Cheers.
</blockquote></details>

Done.

---

**Comment by MichelDiz** [comment]
@codyrobert Thank you.

I believe that 'Learn'> 'Interactive Tour' is kind of off the beaten track for a new user. They can get lost.

Take for example https://www.apollographql.com/
Click in "Start the Tutorial".
See that it is under Apollo's website https://www.apollographql.com/docs/tutorial/introduction/
Click in the logo and you get back to the main page of the docs. Which has the tutorial beginning there.

In our case, we are not putting the tour in the docs. But the logic is the same. The tour used to be a separate site. And by logic, when we use it, it feels a separated thing. For me feels odd (in a UX perspective) to go 'Learn'> 'Interactive Tour'. That's just my two cents. I'm just concerned about the new coming users experience. It is not a blocker for me tho.

To investigate about number 6, you can checkout to some recent branch and see how it works. But again, It is not a blocker for me that too.

Cheers.

**Comment by MichelDiz** [comment]
@codyrobert you may add the Tutorial home at `page-subnav__header`

**Comment by codyrobert** [comment]
Sure! I added a link to the header title.

**Review by MichelDiz — APPROVED** [review]
:lgtm:

> Reviewed 59 of 63 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/151#-:-M6f_8qX1074bn_kRYbD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai, @MichaelJCompton, and @MichelDiz)

**Pull request merged**
