### PR TITLE
Clarify what the syntax with @filter looks like

### PR DESCRIPTION
**Pull request by campoy**
I thought you had to wrap the `func: ...` in parenthesis due to the clarification.

Turns out it's actually simpler.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/64)

### CODE REVIEW

**Comment by danielmai** [comment]
As-is, this needs another parentheses. `@filter` is set outside of the root func.

```diff 
-`func: foo(...) @filter(... AND ...)`
+`func: foo(...)) @filter(... AND ...)`
```

But then the parentheses look unbalanced.

**Comment by MichaelJCompton** [comment]
maybe what it needs is the complete syntax, because you really do need that `func` in its own parenthesis

e.g. `query_name(func: ...) @filter(...) { ... }`

**Comment by campoy** [comment]
I agree with @MichaelJCompton that showing the full syntax might be even better.
Updated.

**Review by danielmai — APPROVED** [review]
:lgtm: Feel free to merge, @campoy.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/64#-:-LfLd5jN8i3rKTCy6Q27:bqu12pf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Pull request merged**
