### PR TITLE
[Wait for v1.1 release] fix schema change bug, uid -> [uid]

### PR DESCRIPTION
**Pull request by leechor**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/58)

### CODE REVIEW

**Comment by martinmr** [comment]
Thanks for your change. It looks good but I won't merge it yet since the changes only apply to the 1.1 version, which has not yet been released.

**Comment by MichelDiz** [comment]
This PR can be merged. As this example was removed from the UI. There's no conflicts.

**Comment by paulftw** [comment]
@MichelDiz  @prashant-shahi  no need to wait for 1.1 now. If you guys think this PR can be merged - merge it into master. If the example was removed - please close this PR.

**Comment by MichelDiz** [comment]
The example was removed, but could be revamped. I'll merge it.

**Pull request merged**
