### PR TITLE
Ui/navigation

### PR DESCRIPTION
**Pull request by shrutika2110**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/173)

 

Tour Preview: [Dgraph Preview](https://dgraph-tour-9c90417236-69453.surge.sh)

### CODE REVIEW

**Review by vardhanapoorv — CHANGES_REQUESTED** [review]
I ran it locally seems to be working for different device sizes. In the iPad view everything is visible and usable, hence we should make the Run button accessible there. The other thing is why does it have "445" files as changed? 


> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/173#-:-M9OLffj8I5iP1J_61yy:bwvlxh4)* status: 0 of 445 files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Comment by shrutika2110** [comment]
For now, I have only fixed the top nav. I have added some jquery in dgraph.js and run the build command.

**Comment by vardhanapoorv** [comment]
Sure. Which all files did you change? So that I can take a look.

**Comment by shrutika2110** [comment]
sure. I have added js in themes/hugo-tutorials/static/js/dgraph.js file, added all menu in themes/hugo-tutorials/layouts/partials/page_nav.html and also added hamburger icon for mobile in themes/hugo-tutorials/layouts/partials/page_header.html file.

**Review by vardhanapoorv — APPROVED** [review]
:lgtm: 

> Reviewed 445 of 445 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/173#-:-M9TTL7M6wpT9j48w9OV:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Comment by shrutika2110** [comment]
can you please merge this changes?

**Pull request merged**
