### PR TITLE
[Basic 5] Fix friend's names retrieval

### PR DESCRIPTION
**Pull request by mrcasals**
The current code only returns Michael, Sarah and Catalina nodes, which are the ones that have the name only in English. In order to return them all, we must add the `@.` part.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/97)

### CODE REVIEW

**Comment by MichelDiz** [comment]
LGTM

@mrcasals  Are you facing this issue? https://github.com/dgraph-io/tutorial/issues/100

**Comment by mrcasals** [comment]
> @mrcasals Are you facing this issue?

Yes, I am with the `master` branch. I'll move the discussion to the linked issue!

**Comment by mrcasals** [comment]
I didn't notice the issue you linked @MichelDiz because at that point I was using the stable branch, which works properly (https://tour.dgraph.io/basic/5/)

**Comment by MichelDiz** [comment]
@mrcasals would you mind to add a little explanation of the `@.` tag usage? This isn't treated anywhere. Can confuse others.

**Comment by mrcasals** [comment]
Will do! Hopefully tomorrow I'll have some spare time to work on it 😄

**Pull request merged**
