### PR TITLE
[Intro 6] Fix: Retrieve pets

### PR DESCRIPTION
**Pull request by mrcasals**
In `intro/6`, the text says:

> In the resulting graph, circles denote people and pets, and lines denote connections or labeled relationships between them. See if you can find Michael and his pet sheep, Rammy.

But the query is not fetching pets, so I can't find Rammy.

This PR fetches pets for Michael and his friends. Since I'm starting, I don't know if there's a better way to do it, feel free to modify the code if so!

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/96)

### CODE REVIEW

**Comment by MichelDiz** [comment]
Hey @mrcasals, thanks for reviewing it.
About this, the only thing is missing is the `owns_pet: [Animal]` in the type.
So I'd suggest that you change only the https://tour.dgraph.io/intro/3/
e.g:
```
type Person {
    name: string
    age: int
    friend: [Person]
    owns_pet: [Animal]
}
```

**Comment by mrcasals** [comment]
So, if I understand this right, this would make the `expand(_all_)` parts of the query be aware of the `owns_pet` field in the type, so it would automatically expand it, right? But how would it expand for the root node ("Michael")?

**Comment by MichelDiz** [comment]
As far as I know about this part of the tutorial, showing Root pets was never the intention. The root is limited to its friend and name edges, no need of showing his pet.

If the intention was to expand everything, we would do:
`expand(_all_){expand(_all_){expand(_all_)}}`
This would expand almost recursively.

**Comment by MichelDiz** [comment]
I can find Michael and his pet sheep, Rammy using the expand example. So this PR isn't necessary.

Thanks!

Cheers.

**Pull request closed without merging**
