### PR TITLE
Fix the JSON mutation to be in sync with RDF mutation (schema/2)

### PR DESCRIPTION
**Pull request by mangalaman93**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/78)

### CODE REVIEW

**Comment by MichelDiz** [comment]
I believe it should be the other way around. We should set "name" in RDF example. Because it is friendlier. I only did it in JSON because it would be more friendly to view.

**Comment by danielmai** [comment]
Let's update the RDF to match the JSON format like @MichelDiz suggests.

**Comment by mangalaman93** [comment]
RDF is the source of truth, that's what we are using to perform the mutation in the tour. JSON mutation is only there for illustration purposes. If I change the RDF mutation, I will need to look at the rest of the queries in the tour and make sure their response is not different anymore. Tour seems to work fine without the name predicate.

**Review by manishrjain — COMMENTED** [review]
I don't have the full context here, but please treat JSON as 1st class citizen. Much fewer people understand RDF.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/78#-:-LkVrSp19KL27e3ncFNw:b-u3xq77)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @MichaelJCompton and @MichelDiz)

**Review by danielmai — APPROVED** [review]
Right now the JSON in schema/2 has more information than the RDF mutation.

The requested change for this PR is to make the JSON and RDF mutation logically equivalent.

Before I thought it was a good idea to add the `name` edge to this section of the tour so that the names in the blank nodes of the mutation are persisted as the `name` edge, e.g., `_:jack <name> "Jack" .` saves the information of the fact that `_:jack` as a blank node is Jack in the database.

But now I think we should submit the PR as-is and remove the name edge. We don't use these names in the schema section of the tour and we already tell the user that blank nodes are converted to assigned UIDs already.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/78#-:-Lka6EtU4YLLIAyKlaKw:b-d98f44)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @MichaelJCompton and @MichelDiz)

**Review by danielmai — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/78#-:-Lka6JiW7AKJBb7crDa9:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @MichaelJCompton and @MichelDiz)

**Review by MichelDiz — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Pull request merged**
