### PR TITLE
Changing schema is alter and not a mutation

### PR DESCRIPTION
**Pull request by sboorlagadda**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/22)

### CODE REVIEW

**Comment by sboorlagadda** [comment]
@pawanrawal Get to this when you have time. I did added a warning in moredata/1.md about increasing memory rather than actually changing docker commands in intro/2. Not sure every user would start trying it in a higher config machine.

**Comment by pawanrawal** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[content/moredata/1.md, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/tutorial/22#-L5GZOTwx0_XqT34IJUy:-L5GZOTxBfBhHuVpiRrl:balwufu) ([raw file](https://github.com/dgraph-io/tutorial/blob/79418b321fa0d914781be964bcdfe88c3863ad3b/content/moredata/1.md#L30)):*
> ```Markdown
> 
> Run the schema mutation using the run button and then load the dataset
> into Dgraph from the terminal. You may be required to restart the server with `--memory_mb 4096` in order to handle bigger dataset. 
> ```

This should be ok. We anyway take more memory than what is specified in `memory_mb`.

---

*[content/schema/3.md, line 10 at r1](https://reviewable.io:443/reviews/dgraph-io/tutorial/22#-L5GZY_o_RjjzjwoSHiL:-L5GZY_o_RjjzjwoSHiM:byn3dso) ([raw file](https://github.com/dgraph-io/tutorial/blob/79418b321fa0d914781be964bcdfe88c3863ad3b/content/schema/3.md#L10)):*
> ```Markdown
> 
> 
> Dgraph doesn't support directly setting the IDs of nodes.  If an application requires unique identifiers for nodes other than the UID assigned by Dgraph, then these have to be supplied as edges.  It's up to a user application to ensure the uniqueness of such IDs/keys.
> ```

This is confusing. We should say external ids and not jus IDs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/tutorial/22)*

**Comment by sboorlagadda** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[content/moredata/1.md, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/tutorial/22#-L5GZOTwx0_XqT34IJUy:-L5GjGZ8Z7NlAU7aKJ6G:bnbo54c) ([raw file](https://github.com/dgraph-io/tutorial/blob/79418b321fa0d914781be964bcdfe88c3863ad3b/content/moredata/1.md#L30)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This should be ok. We anyway take more memory than what is specified in `memory_mb`.
</blockquote></details>

Thats not what I experience all the time. Importing 1million.rdf.gz is success with 4gigs.

---

*[content/schema/3.md, line 10 at r1](https://reviewable.io:443/reviews/dgraph-io/tutorial/22#-L5GZY_o_RjjzjwoSHiL:-L5GkQiyQv5IF_JC349g:b-896fix) ([raw file](https://github.com/dgraph-io/tutorial/blob/79418b321fa0d914781be964bcdfe88c3863ad3b/content/schema/3.md#L10)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This is confusing. We should say external ids and not jus IDs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/tutorial/22)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/tutorial/22#-:-L5I24MJTdsnbpkJgY0F:bnfp4nl)*

**Pull request merged**
