### PR TITLE
Adds RunnableUrl (editable Dgraph Alpha URLs)

### LINKED ISSUE #52: Add ability to change DGraph URL in tour.dgraph.io
New users can stumble into this impasse. When the user does not have Hyper-V or there is a need to install Docker on another machine or even on a virtual machine. There is no way for the user to practice Dgraph through the Tour. Because Dgraph points to Localhost. Dgraph installed on a virtual machine will come with an IP of the virtual machine and not the host IP.

It would be necessary to be able to change the address that the Tour triggers the queries, mutations and alters.

### PR DESCRIPTION
**Pull request by GabeStah**
# Summary

Fixes #52 

All `Runnable` dialogs throughout site can **optionally** provide users the ability to customize the Dgraph URL posted to during a transaction request.

RunnableUrl Demo

Provides full backward compatibility, so there's no need to enable the feature, nor to adjust any front matter settings within the various tour page `.md` files.  Default values are used throughout, allowing standard out-of-the-box functionality.

## Toggling Editable URLs

To enable editable URLs edit the Hugo configuration (`config.toml`) and set the `RunnableUrlEnabled` param to `true`.

```toml
[params]
  RunnableUrlEnabled = true
```

Any other value (or a missing entry) will disable editable URLs and use the default behavior.

## RunnableUrl

The [`RunnableUrl`](https://github.com/GabeStah/tour.dgraph.io/tree/add-runnable-url/themes/hugo-tutorials/static/js/runnable-url/index.js) class represents a robust Runnable URL object. It has the following fields and default values.

```js
class RunnableUrl {
  hash: '',
  hostName: '127.0.0.1',
  port: '8080',
  pathName: '/query',
  pathType: 'query',
  protocol: 'http:',
  search: '',
  searchParams: {},
  statics: {
    searchParams: {
      latency: true
    }
  }
}
```

Each field has a named getter/setter so values can be easily changed or retrieved. A `RunnableUrl` instance is then used to generate the full Dgraph Runnable URL using the `RunnableUrl.url` getter or the `RunnableUrl.toString()` method.

```js
const default = new RunnableUrl();
console.log(default.url);
// http://127.0.0.1:8080/query
```

## Defining Static Properties

The `RunnableUrl` class also has a field called `statics` that is an `Object` collection of property values that should be associated with and included in _every_ `RunnableUrl` instance. However, any properties of the `statics` property object **are not** visible to (or editable by) the user. For example, if every request should include a `latency=true` search parameter, in addition to whatever other user-modifications are made, the `statics` object might look like the following example.

```js
const instance = new RunnableUrl({
  searchParams: {
    foo: 'bar'
  },
  statics: {
    searchParams: {
      latency: true
    }
  }
});

console.log(instance.url);
// returns 'http://127.0.0.1:8080?foo=bar'
// UI shows above URL and allows editing of that URL, without exposing statics.

console.log(RunnableUrl.factory(instance, instance.statics).url);
// returns 'http://127.0.0.1:8080?foo=bar&latency=true'
// Passing statics to temp factory instance allows inclusion of hidden static properties.
```

## Handling Endpoint-Specific User Settings

In many situations, the user may need to override a small selection of properties that make up the overall Alpha URL. RunnableUrl intelligently parses and extracts all components of a valid URL and overrides default properties with any matching user-specified properties. However, it is necessary to differentiate between URLs and settings for each of the potential Alpha endpoints (e.g. `/query`, `/mutate`, `/alter`, etc).

RunnableUrl handles this by tracking each Alpha endpoint as a separate instance, each of which is uniquely editable by the user. Therefore, while the default URL for a `query` transaction will post to the `http://127.0.0.1:8080/query` URL, the user can override every component of the `query` URL, including the endpoint/pathname. For example, even if the user updates the `query` URL to `https://example.com:5432/runQuery?name=Alice` RunnableUrl will remember that this URL is associated with `query` transactions and will use this URL for all runnable requests that default to a `/query` endpoint type.

RunnableUrl determines the transaction type of a runnable instance through the Hugo front matter `endpoint` (or `pathName`) property. If the Hugo `endpoint` property is not specified then RunnableUrl assumes and defaults to a `/query` transaction type.

## Retaining User Data via RunnableStorage

The [`RunnableStorage`](https://github.com/GabeStah/tour.dgraph.io/tree/add-runnable-url/themes/hugo-tutorials/static/js/runnable-url/storage.js) class provides a RunnableUrl instance with helper methods to save and load its data via the browser's [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).

For example, the `RunnableUrl.save()` method serializes its data to JSON then uses `RunnableStorage` to save it to disk.

```js
// ...
save() {
  RunnableStorage.set(
    `${this.constructor.name}-${this.pathType}`,
    JSON.stringify(this.toJSON())
  );
}
// ...
toJSON() {
  return {
    hash: this.hash,
    hostname: this.hostname,
    port: this.port,
    pathname: this.pathname,
    protocol: this.protocol,
    search: this.search,
    searchParams: this.searchParams,
    statics: this.statics
  };
}
```

The `static` `RunnableUrl.load()` method retrieves any existing saved data and deserializes it to create a `RunnableUrl` instance from that data.

```js
static load(overrides = {}) {
  return new this(
    JSON.parse(RunnableStorage.get(this.prototype.constructor.name)),
    overrides
  );
}
```

This retains state information for all user-defined fields between page loads across the app.

## Interface

The [`runnable.html`](https://github.com/GabeStah/tour.dgraph.io/tree/add-runnable-url/themes/hugo-tutorials/layouts/partials/runnable.html) partial checks if the `RunnableUrlEnabled` flag is set to `true` in the site config. If so, it includes the [`runnable-url.html`](https://github.com/GabeStah/tour.dgraph.io/tree/add-runnable-url/themes/hugo-tutorials/layouts/partials/runnable-url.html) partial, otherwise everything is left as default.

```html
{{ if .RunnableUrlEnabled }} {{ partial "runnable-url.html" . }} {{ else }}
<span class="pane-title">
  Endpoint: {{ $endpoint }}
</span>
{{ end }}
```

## (Optional) Front Matter Variables

Each individual post or page that uses a Runnable element can also specify optional front matter params to alter the _initial_ properties of the generated Dgraph URL. The following is the list of possible front matter variables that `RunnableUrl` will look for and use.

- `protocol`
- `hostName`
- `port`
- `endpoint` - Retained for backwards compatibility. `endpoint` and `pathName` are interchangeable, so only one must be specified to alter the pathname of the URL.
- `pathName`
- `search`
- `hash`

**Note: User-specified values will always override front matter values.**

For example, here are the default front matter variables for the [https://tour.dgraph.io/intro/3/](https://tour.dgraph.io/intro/3/) page.

```md
+++
date = "2017-04-26T22:28:55+10:00"
next = "/intro/4"
prev = "/intro/2"
title = "Load Schema"
weight = 3
endpoint = "/alter"
+++
```

RunnableUrl will generate the following URL for the `alter` endpoint transaction: `http://127.0.0.1:8080/alter?latency=true`. However, the `static` property includes `searchParams: { latency: true }` by default, which means the URL displayed to the user in the view is: `http://127.0.0.1:8080/alter`.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/59)

### CODE REVIEW

**Review by MichelDiz — COMMENTED** [review]
This is actual amazing. But can I ask you two changes? When the user don't have a local Dgraph running it throws an error "Error: Is Dgraph running locally?" could you add a "tip" for this feature? also when the user change it and the addr isn't right or something the execution take some time and then throws the error. This isn't critical or something but maybe we could warn something like "is taking too long, are you sure Dgraph is ready?" and then throws the original error.

BTW, I've tested locally with Docker and is perfect.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/59#-:-LemCi5T3kSGTeOZ6WJv:b-brdtq6)* status: 0 of 12 files reviewed, all discussions resolved

**Comment by GabeStah** [comment]
Thanks for looking it over Michel!

> This is actual amazing. But can I ask you two changes? When the user don't have a local Dgraph running it throws an error "Error: Is Dgraph running locally?" could you add a "tip" for this feature?

Sure, I'll see if I can modify the default error message when RunnableUrl is enabled to inform the user that they can change the URLs.

> also when the user change it and the addr isn't right or something the execution take some time and then throws the error. This isn't critical or something but maybe we could warn something like "is taking too long, are you sure Dgraph is ready?" and then throws the original error.

Hmm, can you give a specific example of how you see this working?  The [runnable.js#dgraphPost](https://github.com/dgraph-io/tutorial/blob/master/themes/hugo-tutorials/static/js/runnable.js#L103) function uses the [jQuery.post()](https://api.jquery.com/jquery.post/) method to make an XMLHttpRequest to Dgraph, which seems to have a default timeout period of exactly `1` second.  Thus, when executing a `Runnable` transaction targetting an invalid Alpha URL the **response** window displays `"Waiting for the server response..."` for one second, after which it displays the default error you mentioned above (`"Error: Is Dgraph running locally?"`).

Given that this is already a pretty short window in which to display additional information, can you elaborate a bit on what you'd like to see added or changed to this existing process?

Thanks!

**Comment by MichelDiz** [comment]
I've tested locally pointing to a nonexistent IP. Like http://192.168.99.101 (my docker is http://192.168.99.100) - It took way more than 1s to throw the error. Not sure why.

In my test did not appear "Waiting for the server response..." only the standard error after a period of waiting.

One more thing. By logic the tour should run in a unique address (unique Alpha). I'm not sure why use four fields. There's a motive?

**Comment by GabeStah** [comment]
> I've tested locally pointing to a nonexistent IP. Like http://192.168.99.101 (my docker is http://192.168.99.100) - It took way more than 1s to throw the error. Not sure why.

Ah, I see what you're seeing now.  Yeah, it looks like a nonexistent IP takes 20 (+1) seconds to timeout, whereas an existent IP but an invalid Alpha endpoint (i.e. `127.0.0.1`) just takes the base 1 second to timeout.  So, now I see what you're saying, as there's plenty of time to insert an additional error.

That said, that's actually part of Runnable itself, not the RunnableUrl module, so I think I'll probably want to make that change in a separate pull request from this one.  Let me know if you think otherwise.

> One more thing. By logic the tour should run in a unique address (unique Alpha). I'm not sure why use four fields. There's a motive?

Yes, I explain this a bit in the "Handling Endpoint-Specific User Settings" section of the top comment above.  The basic idea is that a given Runnable might target the `/query` endpoint, while a different Runnable is targetting the `/mutate` endpoint, for example.  Since the RunnableUrl has to be backward compatible and I didn't want to require any modifications to the existing `.md` front matter `endpoint` values, I needed a way to differentiate between settings based on those "targetted" endpoints.

Differentiating custom URLs based on the transaction type allows a user to override settings for that particular type of transaction (similar to how to Dgraph defaults to adding `?latency=true` params).  Furthermore, I didn't want to assume that every user will be targetting requests at the exact same host, port, or path that Dgraph Alpha assumes or defaults to.  For example, a user might have a configuration that sends requests through a proxy -- which itself may act as a middleware to log requests or whatnot -- before forwarding those requests on to Alpha.  Their own proxy path for queries might not be `/query`, or it might not even be the same host that mutations or alteration transactions go through.

While this level of customization is probably fairly unlikely for most users, particularly for the _Tour_, I wanted to make this solution broad enough that it can be plugged into to other Runnable instances fairly easily, such as on the docs, blog, and whatever else.

**Comment by MichelDiz** [comment]
For me is LGTM.

**Comment by GabeStah** [comment]
Per @MichelDiz suggestion latest commit adds a custom error message while RunnableUrl is enabled, along with an animation to highlight the editable button.

RunnableUrl Error Demo

**Comment by danielmai** [comment]
@MichaelJCompton can you review this too?

**Review by danielmai — CHANGES_REQUESTED** [review]
This feature looks great, @GabeStah. Is there a way to reset the URLs to the default values? That way I can revert back to a known good state in case I truly mess up the endpoints in my browser session.

I'm not totally sold on changing the names in the endpoint button (e.g., "/query" &rarr; "q"). I find it confusing that it's no longer clear which Dgraph endpoint will be hit when I click on Run unless I either remember what I changed or open the form and find the corresponding endpoint path. On the other hand, there's some sense in showing that the "Endpoint:" matches the endpoint that's specified. It's also rare for someone to change the endpoint (most will stick with 127.0.0.1:8080) that my concern is probably moot. I'll leave it to you to ultimately decide.

Nitpick/request: Is it possible to avoid the quick flash of "/..." on the initial page load?

> Reviewed 7 of 12 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/59#-:-Lf35BLpCoico-rOmaUN:b-lzjr9s)* status: all files reviewed, 1 unresolved discussion (waiting on @GabeStah and @MichaelJCompton)

___
*[themes/hugo-tutorials/README.md, line 77 at r2](https://reviewable.io/reviews/dgraph-io/tutorial/59#-Lf38CJ33zPyRt_xb107:-Lf38CJ33zPyRt_xb108:b-hheirf) ([raw file](https://github.com/dgraph-io/tutorial/blob/d1ec485239afd77679963080511b8c3817c4caa5/themes/hugo-tutorials/README.md#L77)):*
> ```
> makeup
> ```
make up (verb phrase is two words).

**Review by GabeStah — COMMENTED** [review]
Thanks for the feedback @danielmai.  I added a `Load Defaults` button to the modal to support resetting to default URLs.

Regarding the display of customized endpoint paths I personally feel that a user that changes from the default path is probably advanced enough to recognize that change in the front-end UI/button.  However, I figure there's no reason to have this set in stone, so I added a `displayCustomEndpoint` param to the Hugo configuration.  The default of `true` shows the customized endpoint path to the user (e.g. `/q`), while a value of `false` will always display the default endpoint type path (i.e. `/query`).  See [README#configuration](https://github.com/GabeStah/tour.dgraph.io/blob/add-runnable-url/themes/hugo-tutorials/README.md#configuration) for details.

Unfortunately, getting rid of the `...` flash on load is not feasible.  You probably notice that the `...` flash is visible during the same render period of the main Runnable code content.  Even with RunnableUrl disabled (or viewing the  current`tour.dgraph.io` site) the Runnable code content loads slightly after the rest of the page draw (since it uses an IIFE and has to load the content on-the-fly).  The addition of loading the RunnableUrl module increases load time slightly (less than 100ms increase on my machine), but since it has to tie into the `runnable.js` code anyway, there's no reasonable way to render the endpoint path prior to finishing the `runnable.js` code draw render.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/59#-:-Lf9GsQW39-EIjAc8R8c:bblc8n9)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @danielmai and @MichaelJCompton)

___
*[themes/hugo-tutorials/README.md, line 77 at r2](https://reviewable.io/reviews/dgraph-io/tutorial/59#-Lf38CJ33zPyRt_xb107:-Lf9GhAg7iDrBze-Hto7:b-896fix) ([raw file](https://github.com/dgraph-io/tutorial/blob/d1ec485239afd77679963080511b8c3817c4caa5/themes/hugo-tutorials/README.md#L77)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> makeup
> ```
make up (verb phrase is two words).
</blockquote></details>

Done.

**Review by danielmai — APPROVED** [review]
Thanks for making these changes, @GabeStah! This looks ready to merge to me. Let me know if this is ready and I can merge this for you.

:lgtm:

> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/59#-:-LfAqKaY0W8J9EvkB807:b3gyvdd)* status: 6 of 14 files reviewed, all discussions resolved (waiting on @danielmai and @MichaelJCompton)

**Review by GabeStah — COMMENTED** [review]
Yessir, it looks ready to me.  Thanks @danielmai!

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/59#-:-LfB4li22gkwaNaSniWJ:b-sxo2yz)* status: 6 of 14 files reviewed, all discussions resolved (waiting on @danielmai and @MichaelJCompton)

**Comment by danielmai** [comment]
Merged and live at https://tour.dgraph.io 🎉!

**Pull request merged**
