### PR TITLE
[Intro 4] Properly set type for "Perro" dog

### PR DESCRIPTION
**Pull request by mrcasals**
The tour has a typo on the `intro/4` chapter. It's setting the type for "Goldie" twice, instead of setting it for "Perro".

This PR should fix this issue.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/95)

### CODE REVIEW

**Comment by danielmai** [comment]
Thanks for the PR, @mrcasals!

**Review by danielmai — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/95#-:-LpiZN2pDrpC5P9yFizt:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Review by danielmai — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Comment by mrcasals** [comment]
Thanks for merging it! 😄

**Pull request merged**
