### PR TITLE
Change rebuild behavior.

### PR DESCRIPTION
**Pull request by MichelDiz**
added some instructions.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/146)

 

Tour Preview: [Dgraph Preview](https://dgraph-tour-52716c79cc-59237.surge.sh)

### CODE REVIEW

**Review by danielmai — COMMENTED** [review]
What's the reason for making `git commit` an extra step to run?

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/146#-:-M62deSt521vc-gDMyYx:bkcdytb)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @danielmai and @MichaelJCompton)

**Comment by MichelDiz** [comment]
@danielmai as the master is now protected. We can't send commits to master. And if we run the rebuild script in a branch. It would commit somewhere else(master).

**Review by danielmai — COMMENTED** [review]
Shouldn't we keep the commit step? The current build script would still work in the branch `yourName/rebuildBranches`, right? I see that the important change in this PR is the instruction to create a separate branch for a PR.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/146#-:-M62eOa36AdKDd4IozhC:b-n5xdra)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Comment by MichelDiz** [comment]
@danielmai if you confirm that you are able to commit a rebuild in a branch (not in master). Alright, I'll revert the commit and let only the readme changes. But I have tried and all the time it fails. The first time it had committed on the master, another time committed on 1.0.16. It feels like it was random. Maybe my steps are wrong? dunno.

**Pull request closed without merging**
