### PR TITLE
Add info related to PR dgraph#4531

### PR DESCRIPTION
**Pull request by animesh2049**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/120)

 

Tour Preview: [Dgraph Preview](https://dgraph-tour-042d71746c-42104.surge.sh)

### CODE REVIEW

**Review by campoy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/120)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @animesh2049, @campoy, and @MichaelJCompton)

___
*[content/basic/6.md, line 37 at r1](https://reviewable.io/reviews/dgraph-io/tutorial/120#-Lyk931wCPLQqykksCDR:-Lyk931wCPLQqykksCDS:b-tisrso) ([raw file](https://github.com/dgraph-io/tutorial/blob/7ca660752c0679e34a51a84f82e4fe46ac845304/content/basic/6.md#L37)):*
> ```Markdown
>   but those are bigger topics that'll have their own section in the tutorial
> 
> Functions can only be applied to predicates that have been indexed except
> ```

These comparison functions can ...

(`uid` and `has` are also function and do not require an index)
___
*[content/schema/1.md, line 19 at r1](https://reviewable.io/reviews/dgraph-io/tutorial/120#-Lyk7rDkD-lqtDNO9gVe:-Lyk7rDl8fLJc1gY9x74:b-2a0a7x) ([raw file](https://github.com/dgraph-io/tutorial/blob/7ca660752c0679e34a51a84f82e4fe46ac845304/content/schema/1.md#L19)):*
> ```
> comparision function
> ```
misspelled comparison

> Comparison functions at the query root level (aka `func:`) can only be applied on indexed predicates, which are added by annotating the predicate definition on the schema.
> Since v1.2, comparison functions can now be used on `@filter` directives even on predicates that have not been indexed.

**Review by campoy — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/120)* status: all files reviewed, 2 unresolved discussions (waiting on @animesh2049 and @MichaelJCompton)

**Review by campoy — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/120)* status: all files reviewed, 2 unresolved discussions (waiting on @animesh2049 and @MichaelJCompton)

___
*[content/basic/6.md, line 37 at r1](https://reviewable.io/reviews/dgraph-io/tutorial/120#-Lyk931wCPLQqykksCDR:-LyqFogr7UrlBYESCDdU:b-e4erq) ([raw file](https://github.com/dgraph-io/tutorial/blob/7ca660752c0679e34a51a84f82e4fe46ac845304/content/basic/6.md#L37)):*
<details><summary><i>Previously, campoy (Francesc Campoy) wrote…</i></summary><blockquote>

These comparison functions can ...

(`uid` and `has` are also function and do not require an index)
</blockquote></details>

You forgot this comment.

**Review by MichelDiz — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/120#-:-M0NuTNJCbCkkW-w8mBY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @animesh2049 and @MichaelJCompton)

**Pull request merged**
