### PR TITLE
add notice about Bulk Loader and Live Loader

### PR DESCRIPTION
**Pull request by MichelDiz**

### CODE REVIEW

**Comment by danielmai** [comment]
The note about the bulk loader will be obsolete for v1.1 with live and bulk loader preserving UIDs by default.

**Comment by MichelDiz** [comment]
I see, but Javier added other feature for this. I'll have to elaborate a better argument for this.

**Comment by MichelDiz** [comment]
Hey @danielmai I think isn't the case see "any typo will be considered blank UID". This is not related to this new standard in Bulkload.

If a user has an RDF that was not built by Dgraph itself. And you have a Typo, both the LV and BL will recognize as Blank Node.

With this new pattern "preserving UIDs by default" users who do not use UID must get a new UID by default via blank Node or Typo.

**Comment by danielmai** [comment]
This has been pending for too long. Let's finally merge it.

**Pull request merged**
