### PR TITLE
Add missing predicate actor.film in moredata/2 (issue 122)

### PR DESCRIPTION
**Pull request by zbioe**
More explicit is better.
Add the predicate `actor.film` in schema for better visualization of data.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/124)

 
 

Tour Preview: [Dgraph Preview](https://dgraph-tour-d3bc2d0a98-44981.surge.sh)

### CODE REVIEW

**Comment by MichelDiz** [comment]
Thanks for your contribution.

But as we gonna simplify the Schema. These changes aren't necessary. Please, if you still wanna contribute, you can do it by simplifying the Schema. e.g:

```
type Person {
    name
    director.film
    actor.film
}
```

**Comment by zbioe** [comment]
Many thanks for the opportunity to contribute with this amazing project.

it is something like this change done?

**Review by MichelDiz — APPROVED** [review]
Yes, thank you!

:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/124#-:-M0OGivEEj_EHZrCocWH:byv5zio)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Comment by MichelDiz** [comment]
@iuryfukuda are you using 1.1.0 or 1.1.1?

**Comment by MichelDiz** [comment]
I could not find the PR #4017 in v1.1.0. So I need to revert this commit :/
The right branch is v1.1.1

I should have checked this out before. My bad.

see 
>Simplify type definitions: type definitions no longer require the type (string, int, etc.) per field name. (#4017)

https://github.com/dgraph-io/dgraph/releases/tag/v1.1.1
and https://github.com/dgraph-io/dgraph/releases/tag/v1.1.0

Please Open a PR for the right Branch.

**Comment by zbioe** [comment]
1.1.0, i don't see the version 1.1.1 listing with `git branch -a`:
```
$ git branch -a
* addMissingPredicate
  dgraph-1.1.0
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/addMissingPredicate
  remotes/origin/animesh2049/update-info
  remotes/origin/changeSchema
  remotes/origin/dgraph-1.0.16
  remotes/origin/dgraph-1.1.0
  remotes/origin/master
  remotes/origin/micheldiz/youtube
  remotes/origin/modifytuto
  remotes/origin/removeBadPredicates
```

**Comment by MichelDiz** [comment]
I mean, the version that you are using right now in your machine. Not the branch you're working on.

**Comment by zbioe** [comment]
ok, thank's, no problem, i work on this

**Comment by MichelDiz** [comment]
Oh, okay. The Branch for 1.1.1 doesn't exists at all. Get it. Sorry, I have to do more things about this.
Please, create the PR for master.

Cheers.

**Comment by zbioe** [comment]
no problems,

i open the new PR https://github.com/dgraph-io/tutorial/pull/127

Cheers.

**Pull request merged**
